A:HK3:909:1 times anything:
A:QH8:918:end point:
A:MH4:16:catfish:
A:XZ4:2020:generative grammar:
A:KL0:117:double take:
A:BH7:722:imagination:
A:KT5:3014:aardvark:
A:UT7:2008:zirconium oxide:
A:FA5:221:headless horseman:
A:MZ7:1826:milling machine:
A:RZ5:2015:bookcase:
A:AS2:700:rate of exchange:
A:ZH0:603:unfashionable:
A:KC8:1727:nitrogen narcosis:
A:HA2:319:follow through:
A:ES9:1010:2 times 2 times 2:
A:ZZ8:23:jungle jack:
A:AT4:502:third base:
A:YE6:728:overqualified:
A:BN1:8924:knock-down-drag-out:
A:RE4:4311:3 plus 3 plus 3:
A:VL2:9025:long-distance:
A:XG2:5029:parliamentary law:
A:AF0:707:yankee yawl:
A:ZJ0:1030:quantum number:
A:TG9:4:visual aid:
A:RT8:1212:4 by 4:
A:DF5:101:state university:
A:SP3:8005:ways and means:
A:MT4:1313:5 divided by pi:
A:WA0:5006:x-coordinate:
A:UP7:9999:erehwon:
A:GN2:999:not this time:
A:BN1:99:still can't do it:
S:VL2:
S:UP7:
S:KT5:
S:ZJ0:
S:UU2:
P:
